### ISSUE TITLE
Questions about computing resources

### ISSUE THREAD

**Issue by TT-mouse** [shrutiphutke/spatial_projection_inpainting#1]
Hello, thank you for your excellent work. I would like to ask a question: Does the SPL module in the article require high computing resources for training? Can I train successfully on the RTX3060?

**Comment by shrutiphutke** [comment]
Hi, thanks for your query. I have trained the network on a system with an 8GB GPU by keeping the batch size=1. For your case also it might work on RTX3060.

**Comment by TT-mouse** [comment]
> Hi, thanks for your query. I have trained the network on a system with an 8GB GPU by keeping the batch size=1. For your case also it might work on RTX3060.

Thanks for your reply. I have another question: I saw in the experimental details of your paper that NVIDIA Tesla V100 16 GB GPU was used for model training. What is the reason?

**Comment by shrutiphutke** [comment]
Ya, but we have trained for one dataset on 8 GB GPU also.

**Comment by TT-mouse** [comment]
> Ya, but we have trained for one dataset on 8 GB GPU also.

I see. Thank you!
